version: '3.7'
services:
  app:
    image: myip-app
    build: .
    container_name: myip-app
    
  nginx:
    image: nginx:latest
    container_name: myip-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./client:/var/www/myip
    ports:
      - 8080:80